/**
 * Original teacher-style questions written for Precious PS Academy seed data.
 * Format per item: [topic, difficulty, stem, correct, d1, d2, d3, explanation]
 */
type Row = [string, "EASY" | "MEDIUM" | "HARD", string, string, string, string, string, string];

export const SUBJECT_BANK: Record<string, Row[]> = {
  ENG: [
    ["Vocabulary", "EASY", "Choose the word nearest in meaning to the underlined word: The principal gave a *brief* speech.", "short", "loud", "boring", "formal", "'Brief' means short in duration."],
    ["Vocabulary", "EASY", "Choose the word opposite in meaning to *generous*.", "stingy", "kind", "wealthy", "humble", "A generous person gives freely; the opposite is stingy."],
    ["Grammar", "EASY", "Choose the correct option: Neither the teacher nor the students ___ in the hall.", "were", "was", "is", "has been", "With 'neither…nor', the verb agrees with the nearer subject ('students'), which is plural."],
    ["Grammar", "MEDIUM", "Choose the correct option: If I ___ you, I would apologise.", "were", "was", "am", "had been", "The subjunctive 'were' is used for hypothetical conditions."],
    ["Grammar", "MEDIUM", "Identify the part of speech of the underlined word: She sang *beautifully*.", "adverb", "adjective", "verb", "noun", "'Beautifully' modifies the verb 'sang', so it is an adverb."],
    ["Oral English", "MEDIUM", "Which of these words has a different vowel sound from the others?", "cut", "seat", "feet", "key", "'seat', 'feet' and 'key' contain /iː/; 'cut' contains /ʌ/."],
    ["Concord", "MEDIUM", "Choose the correct option: The number of candidates ___ increased this year.", "has", "have", "were", "are", "'The number of' takes a singular verb."],
    ["Idioms", "MEDIUM", "What does the idiom 'to burn the midnight oil' mean?", "to study or work late into the night", "to waste resources", "to start a fire", "to celebrate at night", "It describes working late, originally by lamplight."],
    ["Punctuation", "EASY", "Which sentence is correctly punctuated?", "Tunde, my cousin, lives in Ibadan.", "Tunde my cousin, lives in Ibadan.", "Tunde, my cousin lives, in Ibadan.", "Tunde my cousin lives in, Ibadan.", "The appositive 'my cousin' is set off by commas on both sides."],
    ["Comprehension skills", "HARD", "A writer's 'tone' in a passage refers to the ___", "attitude of the writer towards the subject", "number of paragraphs", "main characters", "setting of the story", "Tone is the writer's attitude, shown through word choice."],
  ],
  PHY: [
    ["Motion", "EASY", "A car travels 120 km in 2 hours. What is its average speed?", "60 km/h", "240 km/h", "30 km/h", "120 km/h", "Speed = distance ÷ time = 120 ÷ 2 = 60 km/h."],
    ["Motion", "MEDIUM", "A body starts from rest and accelerates uniformly at 2 m/s² for 5 s. Find its final velocity.", "10 m/s", "7 m/s", "2.5 m/s", "25 m/s", "v = u + at = 0 + 2 × 5 = 10 m/s."],
    ["Forces", "EASY", "The SI unit of force is the ___", "newton", "joule", "watt", "pascal", "Force is measured in newtons (N)."],
    ["Work, energy and power", "MEDIUM", "A force of 20 N moves a box through 5 m in the direction of the force. Calculate the work done.", "100 J", "4 J", "25 J", "15 J", "Work = force × distance = 20 × 5 = 100 J."],
    ["Electricity", "MEDIUM", "A 6 Ω resistor carries a current of 2 A. What is the potential difference across it?", "12 V", "3 V", "8 V", "0.33 V", "V = IR = 2 × 6 = 12 V."],
    ["Waves", "MEDIUM", "A wave has frequency 50 Hz and wavelength 4 m. Find its speed.", "200 m/s", "12.5 m/s", "54 m/s", "46 m/s", "v = fλ = 50 × 4 = 200 m/s."],
    ["Heat", "EASY", "Which mode of heat transfer does NOT require a material medium?", "radiation", "conduction", "convection", "evaporation", "Radiation travels as electromagnetic waves, even through a vacuum."],
    ["Pressure", "HARD", "A block of weight 400 N rests on an area of 0.2 m². What pressure does it exert?", "2000 Pa", "80 Pa", "400.2 Pa", "200 Pa", "P = F ÷ A = 400 ÷ 0.2 = 2000 Pa."],
  ],
  CHM: [
    ["Atomic structure", "EASY", "The particle with a positive charge in the nucleus of an atom is the ___", "proton", "electron", "neutron", "photon", "Protons carry a positive charge and are found in the nucleus."],
    ["Atomic structure", "MEDIUM", "An element has atomic number 11 and mass number 23. How many neutrons does it have?", "12", "11", "23", "34", "Neutrons = mass number − atomic number = 23 − 11 = 12."],
    ["Mole concept", "MEDIUM", "What is the molar mass of H₂O? (H = 1, O = 16)", "18 g/mol", "17 g/mol", "34 g/mol", "16 g/mol", "2 × 1 + 16 = 18 g/mol."],
    ["Acids and bases", "EASY", "A solution with pH 2 is ___", "strongly acidic", "neutral", "strongly alkaline", "weakly alkaline", "pH below 7 is acidic; pH 2 is strongly acidic."],
    ["Chemical bonding", "MEDIUM", "The bond formed by transfer of electrons from one atom to another is ___", "ionic (electrovalent) bond", "covalent bond", "metallic bond", "hydrogen bond", "Transfer of electrons produces ions held by electrostatic attraction."],
    ["Separation techniques", "EASY", "Which method is best for separating salt from salt solution?", "evaporation", "filtration", "decantation", "sublimation", "Heating evaporates the water and leaves the salt."],
    ["Periodic table", "MEDIUM", "Elements in the same group of the periodic table have the same ___", "number of valence electrons", "atomic mass", "number of neutrons", "number of shells", "Group number reflects the number of outer-shell electrons."],
    ["Organic chemistry", "HARD", "The general formula of the alkanes is ___", "CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙHₙ", "Alkanes are saturated hydrocarbons with formula CₙH₂ₙ₊₂."],
  ],
  BIO: [
    ["Cell biology", "EASY", "The control centre of a cell is the ___", "nucleus", "cytoplasm", "cell membrane", "vacuole", "The nucleus contains genetic material that controls cell activities."],
    ["Cell biology", "MEDIUM", "Which organelle is the site of aerobic respiration?", "mitochondrion", "ribosome", "chloroplast", "Golgi body", "Mitochondria release energy through aerobic respiration."],
    ["Nutrition", "EASY", "Photosynthesis takes place mainly in the ___", "leaves", "roots", "stem", "flowers", "Leaves contain most of the chlorophyll."],
    ["Ecology", "MEDIUM", "An organism that makes its own food is called a ___", "producer", "consumer", "decomposer", "parasite", "Producers (autotrophs) synthesise food, e.g. green plants."],
    ["Genetics", "HARD", "In a cross between two heterozygous tall plants (Tt × Tt), what fraction of the offspring is expected to be short?", "1/4", "1/2", "3/4", "0", "The offspring ratio is 1 TT : 2 Tt : 1 tt, so 1/4 are short (tt)."],
    ["Human physiology", "MEDIUM", "Which blood vessels carry blood away from the heart?", "arteries", "veins", "capillaries", "venules", "Arteries carry blood away from the heart."],
    ["Classification", "EASY", "Which of the following is a mammal?", "bat", "lizard", "frog", "shark", "Bats have hair and suckle their young — features of mammals."],
    ["Reproduction", "MEDIUM", "The fusion of male and female gametes is called ___", "fertilisation", "pollination", "germination", "ovulation", "Fertilisation is the fusion of gametes to form a zygote."],
  ],
  ECO: [
    ["Basic concepts", "EASY", "The alternative forgone when a choice is made is called ___", "opportunity cost", "real cost", "money cost", "fixed cost", "Opportunity cost is the next best alternative given up."],
    ["Demand and supply", "MEDIUM", "Other things being equal, when the price of a normal good rises, the quantity demanded ___", "falls", "rises", "remains constant", "doubles", "This is the law of demand."],
    ["Market structures", "MEDIUM", "A market with only one seller is called ___", "monopoly", "oligopoly", "perfect competition", "duopoly", "'Mono' means one — a single seller."],
    ["Money", "EASY", "Which of these is NOT a function of money?", "a means of production", "medium of exchange", "store of value", "unit of account", "Money is not itself a factor of production."],
    ["National income", "HARD", "GDP measures the total value of goods and services produced ___", "within a country in a given period", "by citizens abroad only", "by government only", "in the informal sector only", "GDP counts output produced within a country's borders."],
    ["Population", "MEDIUM", "The movement of people from rural to urban areas is known as ___", "rural–urban migration", "emigration", "immigration", "urban renewal", "It describes internal migration from villages to cities."],
  ],
  GOV: [
    ["Basic concepts", "EASY", "The ultimate power of the state to make and enforce laws is ___", "sovereignty", "legitimacy", "authority", "influence", "Sovereignty is supreme, final legal authority."],
    ["Constitution", "MEDIUM", "A constitution that is difficult to amend is described as ___", "rigid", "flexible", "unwritten", "unitary", "A rigid constitution needs a special procedure to amend."],
    ["Arms of government", "EASY", "The arm of government responsible for interpreting laws is the ___", "judiciary", "legislature", "executive", "civil service", "Courts interpret laws."],
    ["Democracy", "MEDIUM", "The principle that no one is above the law is known as ___", "rule of law", "separation of powers", "checks and balances", "delegated legislation", "Rule of law means equality before the law."],
    ["Federalism", "MEDIUM", "In a federal system, power is shared between ___", "central and component governments", "the president and the courts", "political parties", "the army and police", "Federalism divides powers between levels of government."],
    ["Citizenship", "EASY", "Which of these is a duty of a citizen?", "paying taxes", "right to vote", "freedom of speech", "right to life", "Paying taxes is a duty; the others are rights."],
  ],
  CMP: [
    ["Computer fundamentals", "EASY", "Which of these is an input device?", "keyboard", "monitor", "printer", "speaker", "A keyboard sends data into the computer."],
    ["Computer fundamentals", "EASY", "The 'brain' of the computer is the ___", "CPU", "RAM", "hard disk", "monitor", "The CPU executes instructions."],
    ["Data representation", "MEDIUM", "How many bits make one byte?", "8", "4", "16", "1024", "1 byte = 8 bits."],
    ["Networks", "MEDIUM", "A network covering a small area such as a school is a ___", "LAN", "WAN", "MAN", "PAN", "Local Area Network."],
    ["Internet safety", "MEDIUM", "Which is the safest practice for passwords?", "use a long, unique password with letters, numbers and symbols", "use your date of birth", "share it with close friends", "use the same password everywhere", "Long, unique, complex passwords resist guessing."],
    ["Programming", "HARD", "In programming, a loop is used to ___", "repeat a set of instructions", "store data permanently", "connect to the internet", "draw graphics only", "Loops repeat instructions until a condition is met."],
  ],
  CIV: [
    ["Values", "EASY", "Honesty, integrity and respect are examples of ___", "values", "rights", "laws", "customs", "They are principles that guide behaviour."],
    ["Human rights", "MEDIUM", "Which body in Nigeria is primarily set up to protect human rights?", "National Human Rights Commission", "INEC", "NAFDAC", "FRSC", "The NHRC promotes and protects human rights."],
    ["Road safety", "EASY", "The agency responsible for road safety in Nigeria is ___", "FRSC", "EFCC", "NDLEA", "NCC", "Federal Road Safety Corps."],
    ["Drug abuse", "MEDIUM", "The agency responsible for fighting drug trafficking in Nigeria is ___", "NDLEA", "NAFDAC", "SON", "NSCDC", "National Drug Law Enforcement Agency."],
    ["Democracy", "MEDIUM", "Free and fair elections are a feature of ___", "democracy", "dictatorship", "monarchy", "anarchy", "Democracy depends on credible elections."],
  ],
  GEO: [
    ["The earth", "EASY", "The imaginary line dividing the earth into northern and southern hemispheres is the ___", "equator", "prime meridian", "tropic of cancer", "international date line", "The equator is 0° latitude."],
    ["Map reading", "MEDIUM", "On a map with scale 1 : 50 000, 4 cm represents ___", "2 km", "20 km", "200 m", "0.2 km", "4 × 50 000 cm = 200 000 cm = 2 km."],
    ["Climate", "MEDIUM", "The instrument used to measure rainfall is the ___", "rain gauge", "barometer", "hygrometer", "anemometer", "A rain gauge collects and measures rainfall."],
    ["Nigeria", "EASY", "Which river is the longest in Nigeria?", "River Niger", "River Benue", "River Ogun", "River Kaduna", "The Niger is Nigeria's longest river."],
    ["Rocks", "MEDIUM", "Rocks formed from cooled magma are called ___", "igneous rocks", "sedimentary rocks", "metamorphic rocks", "organic rocks", "Igneous rocks form from solidified magma or lava."],
  ],
  COM: [
    ["Trade", "EASY", "Trade between two countries is called ___", "international trade", "home trade", "retail trade", "wholesale trade", "Trade across national borders is international trade."],
    ["Business units", "MEDIUM", "A business owned by one person is a ___", "sole proprietorship", "partnership", "public company", "cooperative", "Sole proprietor = one owner."],
    ["Banking", "MEDIUM", "The apex bank in Nigeria is the ___", "Central Bank of Nigeria", "First Bank", "Bank of Industry", "World Bank", "The CBN regulates banks and issues currency."],
    ["Insurance", "MEDIUM", "The principle of insurance requiring full disclosure of facts is ___", "utmost good faith", "indemnity", "subrogation", "contribution", "Uberrimae fidei — utmost good faith."],
    ["Transport", "EASY", "Which means of transport is most suitable for bulky goods over long distances by land?", "rail", "motorcycle", "air", "bicycle", "Rail carries heavy, bulky goods cheaply over long distances."],
  ],
  ACC: [
    ["Double entry", "EASY", "Every debit entry must have a corresponding ___", "credit entry", "debit entry", "journal", "invoice", "The double-entry principle."],
    ["Accounting equation", "MEDIUM", "If assets are ₦500 000 and liabilities are ₦200 000, what is capital?", "₦300 000", "₦700 000", "₦200 000", "₦500 000", "Capital = Assets − Liabilities = 300 000."],
    ["Books of original entry", "MEDIUM", "Credit purchases of goods are first recorded in the ___", "purchases day book", "sales day book", "cash book", "general journal", "The purchases journal records credit purchases."],
    ["Trial balance", "MEDIUM", "A trial balance is prepared to ___", "check the arithmetical accuracy of the ledger", "show profit", "list customers", "calculate tax", "It tests whether debits equal credits."],
    ["Depreciation", "HARD", "A machine costing ₦100 000 with no residual value is depreciated over 5 years on a straight-line basis. What is the annual depreciation?", "₦20 000", "₦25 000", "₦500 000", "₦10 000", "100 000 ÷ 5 = 20 000 per year."],
  ],
  AGR: [
    ["Soil science", "EASY", "The soil type with the largest particles is ___", "sandy soil", "clay soil", "loamy soil", "silt", "Sand particles are the largest."],
    ["Crop production", "MEDIUM", "Cassava is propagated mainly by ___", "stem cuttings", "seeds", "suckers", "tubers", "Cassava is grown from stem cuttings."],
    ["Animal production", "MEDIUM", "A young female cow is called a ___", "heifer", "calf", "bull", "steer", "A heifer is a young female that has not calved."],
    ["Farm tools", "EASY", "Which tool is used for making ridges?", "hoe", "cutlass", "rake", "shovel", "Hoes are used to make ridges and heaps."],
    ["Pests", "MEDIUM", "Chemicals used to kill weeds are called ___", "herbicides", "insecticides", "fungicides", "rodenticides", "Herbicides kill plants/weeds."],
  ],
};
