/**
 * Builds brand assets from the official Precious PS Academy logo (assets-source/pps-logo-original.jpg):
 *  - logo-full.*   the complete logo lock-up (emblem + wordmark + tagline) on its navy field,
 *  - logo-mark-*   the emblem crop (graduation cap, PP monogram, open book) for small spaces,
 *  - favicon.ico, icon.png, apple-icon.png and PWA / maskable icons,
 *  - src/server/brand-logo.ts  an embedded copy for server-generated PDFs,
 *  - hero-school.jpg  the school building image used on the home page.
 * The Super Admin can replace all of these later from Admin → Branding.
 * Usage: node scripts/brand-assets.mjs assets-source/pps-logo-original.jpg [assets-source/pps-hero-original.jpg]
 */
import sharp from "sharp";
import fs from "node:fs";
import path from "node:path";

const src = process.argv[2];
const heroSrc = process.argv[3] ?? "assets-source/pps-hero-original.jpg";
if (!src) throw new Error("Pass the source logo path");
const out = path.resolve("public/brand");
fs.mkdirSync(out, { recursive: true });

const meta = await sharp(src).metadata();
const W = meta.width, H = meta.height;
const full = await sharp(src).png({ compressionLevel: 9 }).toBuffer();
await sharp(full).resize({ width: 1000 }).png({ compressionLevel: 9 }).toFile(path.join(out, "logo-full.png"));
await sharp(full).resize({ width: 480 }).png({ compressionLevel: 9 }).toFile(path.join(out, "logo-full-480.png"));
await sharp(full).resize({ width: 480 }).webp({ quality: 90 }).toFile(path.join(out, "logo-full-480.webp"));

// Emblem crop (fractions of the source so any resolution works).
const side = Math.round(W * 0.61);
const crest = await sharp(full)
  .extract({ left: Math.round(W * 0.192), top: 0, width: side, height: side })
  .png()
  .toBuffer();
// Tighter crop for favicon sizes: the PP monogram + cap.
const tightSide = Math.round(W * 0.49);
const tight = await sharp(full)
  .extract({ left: Math.round(W * 0.255), top: Math.round(H * 0.055), width: tightSide, height: tightSide })
  .png()
  .toBuffer();
const navy = { r: 10, g: 27, b: 68, alpha: 1 };
const square = async (size, pad = 0, bg = navy) => {
  const inner = Math.round(size * (1 - 2 * pad));
  const r = await sharp(size <= 64 ? tight : crest).resize({ width: inner, height: inner, fit: "cover" }).png().toBuffer();
  return sharp({ create: { width: size, height: size, channels: 4, background: bg } }).composite([{ input: r, gravity: "center" }]).png({ compressionLevel: 9 });
};
for (const s of [16, 32, 48, 64, 128, 192, 256, 512]) await (await square(s)).toFile(path.join(out, `logo-mark-${s}.png`));
await (await square(180)).toFile(path.resolve("src/app/apple-icon.png"));
await (await square(512, 0.1)).toFile(path.join(out, "maskable-512.png"));
await (await square(192, 0.1)).toFile(path.join(out, "maskable-192.png"));
await (await square(64)).toFile(path.resolve("src/app/icon.png"));

const sizes = [16, 32, 48];
const pngs = await Promise.all(sizes.map(async (s) => (await square(s)).toBuffer()));
const header = Buffer.alloc(6 + 16 * sizes.length);
header.writeUInt16LE(0, 0); header.writeUInt16LE(1, 2); header.writeUInt16LE(sizes.length, 4);
let offset = header.length;
sizes.forEach((s, i) => {
  const e = 6 + i * 16;
  header.writeUInt8(s, e); header.writeUInt8(s, e + 1); header.writeUInt8(0, e + 2); header.writeUInt8(0, e + 3);
  header.writeUInt16LE(1, e + 4); header.writeUInt16LE(32, e + 6);
  header.writeUInt32LE(pngs[i].length, e + 8); header.writeUInt32LE(offset, e + 12);
  offset += pngs[i].length;
});
fs.writeFileSync(path.resolve("src/app/favicon.ico"), Buffer.concat([header, ...pngs]));

// Embedded logo for server-generated PDFs (works on serverless without file access).
const pdfLogo = await sharp(full).resize({ width: 320 }).png({ compressionLevel: 9 }).toBuffer();
fs.writeFileSync(
  path.resolve("src/server/brand-logo.ts"),
  `// Generated by scripts/brand-assets.mjs — official Precious PS Academy logo (320px) for PDFs.\nexport const BRAND_LOGO_PNG_BASE64 =\n  "${pdfLogo.toString("base64")}";\n`,
);

if (fs.existsSync(heroSrc)) {
  await sharp(heroSrc).resize({ width: 1600, withoutEnlargement: true }).jpeg({ quality: 84, mozjpeg: true }).toFile(path.join(out, "hero-school.jpg"));
}
console.log("brand assets written", { width: W, height: H });
